[app]
address = ":5000"

[db]
#driver = "mysql"
#connect = "root:@tcp(localhost:3306)/ignite?charset=utf8"
driver = "sqlite3"
connect = "./ignite.db"

[ss]
image = "registry.xiaozhou.net/ssmu:latest"

[host]
address = "localhost"
from = 4000
to = 6000
