[app]
address = ":5000"
log_level = "INFO"

[db]
#driver = "mysql"
#connect = "root:@tcp(localhost:3306)/ignite?charset=utf8"
driver = "sqlite3"
connect = "./data/ignite.db"

[host]
address = "localhost"
from = 5001
to = 6000

[secret]
user = "ignite-user"
admin = "ignite-admin"

[admin]
username = "admin"
password = "123"
